FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN npm set registry https://registry.npmjs.org/ && npm config set fetch-retry-mintimeout 20000 && npm config set fetch-retry-maxtimeout 120000 && npm install

COPY . .

CMD [ "npm", "run", "dev" ]



